plugins {
    id 'java'
    id 'war'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    providedCompile 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    implementation 'mysql:mysql-connector-java:9.3.0'
    implementation 'org.mindrot:jbcrypt:0.4'
}

war {
    archiveFileName = 'demo.war'  // Имя WAR-файла
    from 'src/main/webapp'       // Включаем статические файлы
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'  // Указываем кодировку для компиляции
}

tasks.withType(Javadoc) {
    options.encoding = 'UTF-8'
}

tasks.withType(Test) {
    systemProperty "file.encoding", "UTF-8"
}